/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tsutomu.saito (https://sketchfab.com/tsutomu.saito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tiger-14df664387da4dcf8f2adc9cd0df8641
Title: Tiger
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

const TigerModel = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/tiger.glb");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_26"
                position={[0.679, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.006}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["Material.012"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials["Material.013"]}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials["Material.014"]}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials["Material.015"]}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials["Material.016"]}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials["Material.017"]}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <group name="tiger001_25" />
                </group>
              </group>
              <group
                name="Armature001_69"
                position={[-0.424, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
              >
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <skinnedMesh
                    name="Object_42"
                    geometry={nodes.Object_42.geometry}
                    material={materials["Material.018"]}
                    skeleton={nodes.Object_42.skeleton}
                  />
                  <group name="body001_68" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/tiger.glb");

const Tiger = () => {
  return (
    <Canvas>
      <directionalLight position={[1, 1, 1]} intensity={2} />
      <ambientLight intensity={0.5} />
      <pointLight position={[10, 5, 10]} intensity={2} />
      <spotLight
        position={[0, 50, 10]}
        angle={0.15}
        penumbra={1}
        intensity={2}
      />
      <TigerModel position={[-0.5, -2.5, 0]} scale={[3, 3, 3]} />
    </Canvas>
  );
};

export default Tiger;
